[package]
name = "rust-exercises"
version = "0.1.0"
authors = ["Dennis Duda <git@seri.tools>"]
edition = "2018"

default-run = "rust-exercises"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
